"""Add pending_completion field to UserQuiz

Revision ID: 420ab4b5f5d9
Revises: 9a049c2fe191
Create Date: 2025-06-06 15:27:11.178374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420ab4b5f5d9'
down_revision = '9a049c2fe191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_completion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quizzes', schema=None) as batch_op:
        batch_op.drop_column('pending_completion')

    # ### end Alembic commands ###
