"""Add time_limit to Quiz model

Revision ID: 9a049c2fe191
Revises: 7395ac576caa
Create Date: 2025-06-06 08:59:11.151136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a049c2fe191'
down_revision = '7395ac576caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_quizzes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###
