apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: exam-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: exam-app:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
        env:
        - name: FLASK_APP
          value: "app"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: exam-app-secrets
              key: database-url
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"
        - name: CELERY_RESULT_BACKEND
          value: "rpc://"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: exam-app-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exam-app-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: exam-app-secrets
              key: postgres-db
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
